title: Romblings 3.0 
description: "Astro's Digital Garden"
url: "https://super-palmier-8cd3c5.netlify.app/"
#baseurl: ""

theme: jekyll-bonsai

include:
  - "_pages"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"

collections:
  books:
    output: true
  entries:
    output: true
  states:
    output: true
    order:
      - tags.md
      - sprout.md
      - bud.md
      - bamboo.md
      - bloom.md
      - berry.md
      - fruit.md
      - melon.md
      - seed.md
      - tea.md
      - pot-bamboo.md

# frontmatter
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      permalink: "/post/:id/"
  -
    scope:
      type: "books"
    values:
      layout: "book"
      permalink: "/book/:id/"
  - 
    scope:
      type: "entries"
    values:
      layout: "entry"
      permalink: "/entry/:id/"
  - 
    scope:
      type: "states"
    values:
      layout: "state"
      permalink: "/stat/:id/"


namespaces:
  exclude:
    - "books"
    - "pages"
    - "posts"
    - "states"

bonsai:
  default_theme: "dark"
  nav:
    type: "graph"
    graph:
      type: "tree"
  home:
    notable: 
      enabled: false 
    recent: 
      enabled: true
      cap: 3

social:
  connect:
    enabled: false
  share:
    enabled: false
    type:
      - 'email'
      - 'facebook'
      - 'linkedin'
      - 'twitter'

